name: CI Pipeline

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install Dependencies
        id: cache
        run: npm install

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run ESLint
        run: npx eslint --ext ".js,.ts,.tsx" --ignore-path .gitignore .

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Prettier
        run: npx prettier --check .

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Project
        run: npm run build

  unit_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Unit Tests
        run: npm test

  e2e_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Next.js Server
        run: |
          npm run dev &
          npx wait-on http://localhost:4000

      - name: Run E2E Tests with Playwright
        run: npx playwright test
        env:
          CI: true
